#############################################################################
# Makefile for building: project
# Generated by qmake (1.07a) (Qt 3.3.3) on: Thu Feb 17 02:36:33 2011
# Project:  project.pro
# Template: app
# Command: $(QMAKE) -o Makefile project.pro
#############################################################################

####### Compiler, tools and options

CC		=	cl
CXX		=	cl
LEX		= flex
YACC		= byacc
CFLAGS	=	-nologo -Zm200 -W3 -MD -O1  -DUNICODE -DQT_DLL -DQT_THREAD_SUPPORT -DQT_ACCESSIBILITY_SUPPORT -DQT_NO_DEBUG
CXXFLAGS	=	-nologo -Zm200 -W3 -MD -O1  -DUNICODE -DQT_DLL -DQT_THREAD_SUPPORT -DQT_ACCESSIBILITY_SUPPORT -DQT_NO_DEBUG
LEXFLAGS	=
YACCFLAGS	=-d
INCPATH	=	 -I"$(QTDIR)\include" -I"C:\Qt\3.3.3\projects\project" -I"tmp\moc\release_mt_shared" -I"C:\Qt\3.3.3\mkspecs\win32-msvc"
LINK	=	link
LFLAGS	=	/NOLOGO delayimp.lib /DELAYLOAD:comdlg32.dll /DELAYLOAD:oleaut32.dll /DELAYLOAD:winmm.dll /DELAYLOAD:wsock32.dll /DELAYLOAD:winspool.dll /DELAYLOAD:opengl32.dll /SUBSYSTEM:console /LIBPATH:"$(QTDIR)\lib"
LIBS	=	 "qt-mt333.lib" "qtmain.lib" "opengl32.lib" "glu32.lib" "delayimp.lib" "kernel32.lib" "user32.lib" "gdi32.lib" "comdlg32.lib" "advapi32.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "imm32.lib" "winmm.lib" "wsock32.lib" "winspool.lib"
MOC		=	$(QTDIR)\bin\moc.exe
UIC		=	$(QTDIR)\bin\uic.exe
QMAKE		=	qmake
IDC		=	$(QTDIR)\bin\idc.exe
IDL		=	midl
ZIP		=	zip -r -9
COPY_FILE	=       copy
COPY_DIR	=       copy
DEL_FILE	=       del
DEL_DIR	=       rmdir
MOVE		=       move
CHK_DIR_EXISTS =	if not exist
MKDIR		=	mkdir
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)

####### Files

HEADERS =	mainform.h \
		addplandialog.h \
		removeplandialog.h \
		editplandialog.h \
		addtaskdialog.h \
		edittaskdialog.h \
		referenceform.h \
		selectplandialog.h
SOURCES =	main.cpp \
		mainform.cpp \
		addplandialog.cpp \
		removeplandialog.cpp \
		editplandialog.cpp \
		addtaskdialog.cpp \
		edittaskdialog.cpp \
		referenceform.cpp \
		selectplandialog.cpp
OBJECTS =	tmp\obj\release_mt_shared\main.obj \
		tmp\obj\release_mt_shared\mainform.obj \
		tmp\obj\release_mt_shared\addplandialog.obj \
		tmp\obj\release_mt_shared\removeplandialog.obj \
		tmp\obj\release_mt_shared\editplandialog.obj \
		tmp\obj\release_mt_shared\addtaskdialog.obj \
		tmp\obj\release_mt_shared\edittaskdialog.obj \
		tmp\obj\release_mt_shared\referenceform.obj \
		tmp\obj\release_mt_shared\selectplandialog.obj \
		tmp\obj\release_mt_shared\mainformbase.obj \
		tmp\obj\release_mt_shared\addplandialogbase.obj \
		tmp\obj\release_mt_shared\removeplandialogbase.obj \
		tmp\obj\release_mt_shared\editplandialogbase.obj \
		tmp\obj\release_mt_shared\addtaskdialogbase.obj \
		tmp\obj\release_mt_shared\edittaskdialogbase.obj \
		tmp\obj\release_mt_shared\referenceformbase.obj \
		tmp\obj\release_mt_shared\selectplandialog.obj \
		tmp\obj\release_mt_shared\qmake_image_collection.obj
FORMS =	mainformbase.ui \
		addplandialogbase.ui \
		removeplandialogbase.ui \
		editplandialogbase.ui \
		addtaskdialogbase.ui \
		edittaskdialogbase.ui \
		referenceformbase.ui \
		selectplandialog.ui
UICDECLS =	mainformbase.h \
		addplandialogbase.h \
		removeplandialogbase.h \
		editplandialogbase.h \
		addtaskdialogbase.h \
		edittaskdialogbase.h \
		referenceformbase.h \
		selectplandialog.h
UICIMPLS =	mainformbase.cpp \
		addplandialogbase.cpp \
		removeplandialogbase.cpp \
		editplandialogbase.cpp \
		addtaskdialogbase.cpp \
		edittaskdialogbase.cpp \
		referenceformbase.cpp \
		selectplandialog.cpp
SRCMOC	=	tmp\moc\release_mt_shared\moc_mainform.cpp \
		tmp\moc\release_mt_shared\moc_addplandialog.cpp \
		tmp\moc\release_mt_shared\moc_removeplandialog.cpp \
		tmp\moc\release_mt_shared\moc_editplandialog.cpp \
		tmp\moc\release_mt_shared\moc_addtaskdialog.cpp \
		tmp\moc\release_mt_shared\moc_edittaskdialog.cpp \
		tmp\moc\release_mt_shared\moc_referenceform.cpp \
		tmp\moc\release_mt_shared\moc_selectplandialog.cpp \
		tmp\moc\release_mt_shared\moc_mainformbase.cpp \
		tmp\moc\release_mt_shared\moc_addplandialogbase.cpp \
		tmp\moc\release_mt_shared\moc_removeplandialogbase.cpp \
		tmp\moc\release_mt_shared\moc_editplandialogbase.cpp \
		tmp\moc\release_mt_shared\moc_addtaskdialogbase.cpp \
		tmp\moc\release_mt_shared\moc_edittaskdialogbase.cpp \
		tmp\moc\release_mt_shared\moc_referenceformbase.cpp \
		tmp\moc\release_mt_shared\moc_selectplandialog.cpp
OBJMOC	=	tmp\obj\release_mt_shared\moc_mainform.obj \
		tmp\obj\release_mt_shared\moc_addplandialog.obj \
		tmp\obj\release_mt_shared\moc_removeplandialog.obj \
		tmp\obj\release_mt_shared\moc_editplandialog.obj \
		tmp\obj\release_mt_shared\moc_addtaskdialog.obj \
		tmp\obj\release_mt_shared\moc_edittaskdialog.obj \
		tmp\obj\release_mt_shared\moc_referenceform.obj \
		tmp\obj\release_mt_shared\moc_selectplandialog.obj \
		tmp\obj\release_mt_shared\moc_mainformbase.obj \
		tmp\obj\release_mt_shared\moc_addplandialogbase.obj \
		tmp\obj\release_mt_shared\moc_removeplandialogbase.obj \
		tmp\obj\release_mt_shared\moc_editplandialogbase.obj \
		tmp\obj\release_mt_shared\moc_addtaskdialogbase.obj \
		tmp\obj\release_mt_shared\moc_edittaskdialogbase.obj \
		tmp\obj\release_mt_shared\moc_referenceformbase.obj \
		tmp\obj\release_mt_shared\moc_selectplandialog.obj
DIST	=	
TARGET	=	project.exe

####### Implicit rules

.SUFFIXES: .c .cpp .cc .cxx .C

{.}.cpp{tmp\obj\release_mt_shared\}.obj::
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fotmp\obj\release_mt_shared\ @<<
	$<
<<

{.}.cc{tmp\obj\release_mt_shared\}.obj::
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fotmp\obj\release_mt_shared\ @<<
	$<
<<

{.}.cxx{tmp\obj\release_mt_shared\}.obj::
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fotmp\obj\release_mt_shared\ @<<
	$<
<<

{.}.C{tmp\obj\release_mt_shared\}.obj::
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fotmp\obj\release_mt_shared\ @<<
	$<
<<

{.}.c{tmp\obj\release_mt_shared\}.obj::
	$(CC) -c $(CFLAGS) $(INCPATH) -Fotmp\obj\release_mt_shared\ @<<
	$<
<<

{tmp\moc\release_mt_shared}.cpp{tmp\obj\release_mt_shared\}.obj::
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fotmp\obj\release_mt_shared\ @<<
	$<
<<

{tmp\moc\release_mt_shared}.cc{tmp\obj\release_mt_shared\}.obj::
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fotmp\obj\release_mt_shared\ @<<
	$<
<<

{tmp\moc\release_mt_shared}.cxx{tmp\obj\release_mt_shared\}.obj::
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fotmp\obj\release_mt_shared\ @<<
	$<
<<

{tmp\moc\release_mt_shared}.C{tmp\obj\release_mt_shared\}.obj::
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fotmp\obj\release_mt_shared\ @<<
	$<
<<

{tmp\moc\release_mt_shared}.c{tmp\obj\release_mt_shared\}.obj::
	$(CC) -c $(CFLAGS) $(INCPATH) -Fotmp\obj\release_mt_shared\ @<<
	$<
<<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC) 
	$(LINK) $(LFLAGS) /OUT:$(TARGET) @<< 
	  $(OBJECTS) $(OBJMOC) $(LIBS)
<<


mocables: $(SRCMOC)
uicables: $(UICIMPLS) $(UICDECLS)

Makefile: project.pro ..\..\.qmake.cache C:\Qt\3.3.3\mkspecs\win32-msvc\qmake.conf ..\..\lib\qtmain.prl
	$(QMAKE) -o Makefile project.pro
qmake: 
	@$(QMAKE) -o Makefile project.pro

dist:
	$(ZIP) project.zip $(SOURCES) $(HEADERS) $(DIST) $(FORMS) C:/Qt/3.3.3/projects/project/project.pro ..\..\lib\qtmain.prl  images/block_16.png images/calendar_16.png images/tick_16.png images/delete_16.png images/plus_16.png images/save_16.png images/pencil_16.png

uiclean:
	-$(DEL_FILE) mainformbase.h
	-$(DEL_FILE) addplandialogbase.h
	-$(DEL_FILE) removeplandialogbase.h
	-$(DEL_FILE) editplandialogbase.h
	-$(DEL_FILE) addtaskdialogbase.h
	-$(DEL_FILE) edittaskdialogbase.h
	-$(DEL_FILE) referenceformbase.h
	-$(DEL_FILE) selectplandialog.h
	-$(DEL_FILE) mainformbase.cpp
	-$(DEL_FILE) addplandialogbase.cpp
	-$(DEL_FILE) removeplandialogbase.cpp
	-$(DEL_FILE) editplandialogbase.cpp
	-$(DEL_FILE) addtaskdialogbase.cpp
	-$(DEL_FILE) edittaskdialogbase.cpp
	-$(DEL_FILE) referenceformbase.cpp
	-$(DEL_FILE) selectplandialog.cpp
mocclean:
	-$(DEL_FILE) tmp\moc\release_mt_shared\moc_mainform.cpp
	-$(DEL_FILE) tmp\moc\release_mt_shared\moc_addplandialog.cpp
	-$(DEL_FILE) tmp\moc\release_mt_shared\moc_removeplandialog.cpp
	-$(DEL_FILE) tmp\moc\release_mt_shared\moc_editplandialog.cpp
	-$(DEL_FILE) tmp\moc\release_mt_shared\moc_addtaskdialog.cpp
	-$(DEL_FILE) tmp\moc\release_mt_shared\moc_edittaskdialog.cpp
	-$(DEL_FILE) tmp\moc\release_mt_shared\moc_referenceform.cpp
	-$(DEL_FILE) tmp\moc\release_mt_shared\moc_selectplandialog.cpp
	-$(DEL_FILE) tmp\moc\release_mt_shared\moc_mainformbase.cpp
	-$(DEL_FILE) tmp\moc\release_mt_shared\moc_addplandialogbase.cpp
	-$(DEL_FILE) tmp\moc\release_mt_shared\moc_removeplandialogbase.cpp
	-$(DEL_FILE) tmp\moc\release_mt_shared\moc_editplandialogbase.cpp
	-$(DEL_FILE) tmp\moc\release_mt_shared\moc_addtaskdialogbase.cpp
	-$(DEL_FILE) tmp\moc\release_mt_shared\moc_edittaskdialogbase.cpp
	-$(DEL_FILE) tmp\moc\release_mt_shared\moc_referenceformbase.cpp
	-$(DEL_FILE) tmp\moc\release_mt_shared\moc_selectplandialog.cpp
	-$(DEL_FILE) tmp\obj\release_mt_shared\moc_mainform.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\moc_addplandialog.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\moc_removeplandialog.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\moc_editplandialog.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\moc_addtaskdialog.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\moc_edittaskdialog.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\moc_referenceform.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\moc_selectplandialog.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\moc_mainformbase.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\moc_addplandialogbase.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\moc_removeplandialogbase.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\moc_editplandialogbase.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\moc_addtaskdialogbase.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\moc_edittaskdialogbase.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\moc_referenceformbase.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\moc_selectplandialog.obj
clean: uiclean mocclean
	-$(DEL_FILE) tmp\obj\release_mt_shared\main.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\mainform.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\addplandialog.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\removeplandialog.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\editplandialog.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\addtaskdialog.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\edittaskdialog.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\referenceform.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\selectplandialog.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\mainformbase.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\addplandialogbase.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\removeplandialogbase.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\editplandialogbase.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\addtaskdialogbase.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\edittaskdialogbase.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\referenceformbase.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\selectplandialog.obj
	-$(DEL_FILE) tmp\obj\release_mt_shared\qmake_image_collection.obj
	-$(DEL_FILE) qmake_image_collection.cpp



FORCE:

distclean: clean
	-$(DEL_FILE) $(TARGET)

####### Compile

tmp\obj\release_mt_shared\main.obj: main.cpp  \
		mainform.h \
		mainformbase.h \
		

tmp\obj\release_mt_shared\mainform.obj: mainform.cpp  \
		mainform.h \
		addplandialog.h \
		editplandialog.h \
		removeplandialog.h \
		addtaskdialog.h \
		edittaskdialog.h \
		referenceform.h \
		selectplandialog.h \
		mainformbase.h \
		addplandialogbase.h \
		editplandialogbase.h \
		removeplandialogbase.h \
		addtaskdialogbase.h \
		edittaskdialogbase.h \
		referenceformbase.h \
		selectplandialogbase.h \
		

tmp\obj\release_mt_shared\addplandialog.obj: addplandialog.cpp  \
		addplandialog.h \
		addplandialogbase.h \
		

tmp\obj\release_mt_shared\removeplandialog.obj: removeplandialog.cpp  \
		removeplandialog.h \
		removeplandialogbase.h \
		

tmp\obj\release_mt_shared\editplandialog.obj: editplandialog.cpp  \
		editplandialog.h \
		editplandialogbase.h \
		

tmp\obj\release_mt_shared\addtaskdialog.obj: addtaskdialog.cpp  \
		addtaskdialog.h \
		addtaskdialogbase.h \
		

tmp\obj\release_mt_shared\edittaskdialog.obj: edittaskdialog.cpp  \
		edittaskdialog.h \
		edittaskdialogbase.h \
		

tmp\obj\release_mt_shared\referenceform.obj: referenceform.cpp  \
		referenceform.h \
		referenceformbase.h \
		

tmp\obj\release_mt_shared\selectplandialog.obj: selectplandialog.cpp  \
		selectplandialog.h \
		selectplandialogbase.h \
		selectplandialog.h \
		

mainformbase.h: mainformbase.ui 
	$(UIC) mainformbase.ui -o mainformbase.h

mainformbase.cpp: mainformbase.h mainformbase.ui 
	$(UIC) mainformbase.ui -i mainformbase.h -o mainformbase.cpp

addplandialogbase.h: addplandialogbase.ui 
	$(UIC) addplandialogbase.ui -o addplandialogbase.h

addplandialogbase.cpp: addplandialogbase.h addplandialogbase.ui 
	$(UIC) addplandialogbase.ui -i addplandialogbase.h -o addplandialogbase.cpp

removeplandialogbase.h: removeplandialogbase.ui 
	$(UIC) removeplandialogbase.ui -o removeplandialogbase.h

removeplandialogbase.cpp: removeplandialogbase.h removeplandialogbase.ui 
	$(UIC) removeplandialogbase.ui -i removeplandialogbase.h -o removeplandialogbase.cpp

editplandialogbase.h: editplandialogbase.ui 
	$(UIC) editplandialogbase.ui -o editplandialogbase.h

editplandialogbase.cpp: editplandialogbase.h editplandialogbase.ui 
	$(UIC) editplandialogbase.ui -i editplandialogbase.h -o editplandialogbase.cpp

addtaskdialogbase.h: addtaskdialogbase.ui 
	$(UIC) addtaskdialogbase.ui -o addtaskdialogbase.h

addtaskdialogbase.cpp: addtaskdialogbase.h addtaskdialogbase.ui 
	$(UIC) addtaskdialogbase.ui -i addtaskdialogbase.h -o addtaskdialogbase.cpp

edittaskdialogbase.h: edittaskdialogbase.ui 
	$(UIC) edittaskdialogbase.ui -o edittaskdialogbase.h

edittaskdialogbase.cpp: edittaskdialogbase.h edittaskdialogbase.ui 
	$(UIC) edittaskdialogbase.ui -i edittaskdialogbase.h -o edittaskdialogbase.cpp

referenceformbase.h: referenceformbase.ui 
	$(UIC) referenceformbase.ui -o referenceformbase.h

referenceformbase.cpp: referenceformbase.h referenceformbase.ui 
	$(UIC) referenceformbase.ui -i referenceformbase.h -o referenceformbase.cpp

selectplandialog.h: selectplandialog.ui 
	$(UIC) selectplandialog.ui -o selectplandialog.h

selectplandialog.cpp: selectplandialog.h selectplandialog.ui 
	$(UIC) selectplandialog.ui -i selectplandialog.h -o selectplandialog.cpp

tmp\obj\release_mt_shared\mainformbase.obj: mainformbase.cpp  \
		mainformbase.h \
		

tmp\obj\release_mt_shared\addplandialogbase.obj: addplandialogbase.cpp  \
		addplandialogbase.h \
		

tmp\obj\release_mt_shared\removeplandialogbase.obj: removeplandialogbase.cpp  \
		removeplandialogbase.h \
		

tmp\obj\release_mt_shared\editplandialogbase.obj: editplandialogbase.cpp  \
		editplandialogbase.h \
		

tmp\obj\release_mt_shared\addtaskdialogbase.obj: addtaskdialogbase.cpp  \
		addtaskdialogbase.h \
		

tmp\obj\release_mt_shared\edittaskdialogbase.obj: edittaskdialogbase.cpp  \
		edittaskdialogbase.h \
		

tmp\obj\release_mt_shared\referenceformbase.obj: referenceformbase.cpp  \
		referenceformbase.h \
		

tmp\obj\release_mt_shared\selectplandialog.obj: selectplandialog.cpp  \
		selectplandialog.h \
		selectplandialogbase.h \
		selectplandialog.h \
		

tmp\obj\release_mt_shared\moc_mainform.obj: tmp\moc\release_mt_shared\moc_mainform.cpp  mainform.h mainformbase.h

tmp\obj\release_mt_shared\moc_addplandialog.obj: tmp\moc\release_mt_shared\moc_addplandialog.cpp  addplandialog.h addplandialogbase.h

tmp\obj\release_mt_shared\moc_removeplandialog.obj: tmp\moc\release_mt_shared\moc_removeplandialog.cpp  removeplandialog.h removeplandialogbase.h

tmp\obj\release_mt_shared\moc_editplandialog.obj: tmp\moc\release_mt_shared\moc_editplandialog.cpp  editplandialog.h editplandialogbase.h

tmp\obj\release_mt_shared\moc_addtaskdialog.obj: tmp\moc\release_mt_shared\moc_addtaskdialog.cpp  addtaskdialog.h addtaskdialogbase.h

tmp\obj\release_mt_shared\moc_edittaskdialog.obj: tmp\moc\release_mt_shared\moc_edittaskdialog.cpp  edittaskdialog.h edittaskdialogbase.h

tmp\obj\release_mt_shared\moc_referenceform.obj: tmp\moc\release_mt_shared\moc_referenceform.cpp  referenceform.h referenceformbase.h

tmp\obj\release_mt_shared\moc_selectplandialog.obj: tmp\moc\release_mt_shared\moc_selectplandialog.cpp  selectplandialog.h selectplandialogbase.h

tmp\obj\release_mt_shared\moc_mainformbase.obj: tmp\moc\release_mt_shared\moc_mainformbase.cpp  mainformbase.h 

tmp\obj\release_mt_shared\moc_addplandialogbase.obj: tmp\moc\release_mt_shared\moc_addplandialogbase.cpp  addplandialogbase.h 

tmp\obj\release_mt_shared\moc_removeplandialogbase.obj: tmp\moc\release_mt_shared\moc_removeplandialogbase.cpp  removeplandialogbase.h 

tmp\obj\release_mt_shared\moc_editplandialogbase.obj: tmp\moc\release_mt_shared\moc_editplandialogbase.cpp  editplandialogbase.h 

tmp\obj\release_mt_shared\moc_addtaskdialogbase.obj: tmp\moc\release_mt_shared\moc_addtaskdialogbase.cpp  addtaskdialogbase.h 

tmp\obj\release_mt_shared\moc_edittaskdialogbase.obj: tmp\moc\release_mt_shared\moc_edittaskdialogbase.cpp  edittaskdialogbase.h 

tmp\obj\release_mt_shared\moc_referenceformbase.obj: tmp\moc\release_mt_shared\moc_referenceformbase.cpp  referenceformbase.h 

tmp\obj\release_mt_shared\moc_selectplandialog.obj: tmp\moc\release_mt_shared\moc_selectplandialog.cpp  selectplandialog.h selectplandialogbase.h

tmp\moc\release_mt_shared\moc_mainform.cpp: $(MOC) mainform.h
	$(MOC) mainform.h -o tmp\moc\release_mt_shared\moc_mainform.cpp

tmp\moc\release_mt_shared\moc_addplandialog.cpp: $(MOC) addplandialog.h
	$(MOC) addplandialog.h -o tmp\moc\release_mt_shared\moc_addplandialog.cpp

tmp\moc\release_mt_shared\moc_removeplandialog.cpp: $(MOC) removeplandialog.h
	$(MOC) removeplandialog.h -o tmp\moc\release_mt_shared\moc_removeplandialog.cpp

tmp\moc\release_mt_shared\moc_editplandialog.cpp: $(MOC) editplandialog.h
	$(MOC) editplandialog.h -o tmp\moc\release_mt_shared\moc_editplandialog.cpp

tmp\moc\release_mt_shared\moc_addtaskdialog.cpp: $(MOC) addtaskdialog.h
	$(MOC) addtaskdialog.h -o tmp\moc\release_mt_shared\moc_addtaskdialog.cpp

tmp\moc\release_mt_shared\moc_edittaskdialog.cpp: $(MOC) edittaskdialog.h
	$(MOC) edittaskdialog.h -o tmp\moc\release_mt_shared\moc_edittaskdialog.cpp

tmp\moc\release_mt_shared\moc_referenceform.cpp: $(MOC) referenceform.h
	$(MOC) referenceform.h -o tmp\moc\release_mt_shared\moc_referenceform.cpp

tmp\moc\release_mt_shared\moc_selectplandialog.cpp: $(MOC) selectplandialog.h
	$(MOC) selectplandialog.h -o tmp\moc\release_mt_shared\moc_selectplandialog.cpp

tmp\moc\release_mt_shared\moc_mainformbase.cpp: $(MOC) mainformbase.h
	$(MOC) mainformbase.h -o tmp\moc\release_mt_shared\moc_mainformbase.cpp

tmp\moc\release_mt_shared\moc_addplandialogbase.cpp: $(MOC) addplandialogbase.h
	$(MOC) addplandialogbase.h -o tmp\moc\release_mt_shared\moc_addplandialogbase.cpp

tmp\moc\release_mt_shared\moc_removeplandialogbase.cpp: $(MOC) removeplandialogbase.h
	$(MOC) removeplandialogbase.h -o tmp\moc\release_mt_shared\moc_removeplandialogbase.cpp

tmp\moc\release_mt_shared\moc_editplandialogbase.cpp: $(MOC) editplandialogbase.h
	$(MOC) editplandialogbase.h -o tmp\moc\release_mt_shared\moc_editplandialogbase.cpp

tmp\moc\release_mt_shared\moc_addtaskdialogbase.cpp: $(MOC) addtaskdialogbase.h
	$(MOC) addtaskdialogbase.h -o tmp\moc\release_mt_shared\moc_addtaskdialogbase.cpp

tmp\moc\release_mt_shared\moc_edittaskdialogbase.cpp: $(MOC) edittaskdialogbase.h
	$(MOC) edittaskdialogbase.h -o tmp\moc\release_mt_shared\moc_edittaskdialogbase.cpp

tmp\moc\release_mt_shared\moc_referenceformbase.cpp: $(MOC) referenceformbase.h
	$(MOC) referenceformbase.h -o tmp\moc\release_mt_shared\moc_referenceformbase.cpp

tmp\moc\release_mt_shared\moc_selectplandialog.cpp: $(MOC) selectplandialog.h
	$(MOC) selectplandialog.h -o tmp\moc\release_mt_shared\moc_selectplandialog.cpp

tmp\obj\release_mt_shared\qmake_image_collection.obj: qmake_image_collection.cpp

qmake_image_collection.cpp: images\block_16.png \
		images\calendar_16.png \
		images\tick_16.png \
		images\delete_16.png \
		images\plus_16.png \
		images\save_16.png \
		images\pencil_16.png
	$(UIC)  -o qmake_image_collection.cpp -embed project -f <<
images\block_16.png images\calendar_16.png images\tick_16.png images\delete_16.png images\plus_16.png images\save_16.png images\pencil_16.png
<<

####### Install

install:  

uninstall:  

